"""esquema inicial 5 tablas

Revision ID: 13c6d5cbb9f2
Revises: 
Create Date: 2026-08-19 03:06:25.341461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c6d5cbb9f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marca',
    sa.Column('id_marca', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_marca'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('modelo_cnn',
    sa.Column('id_modelo_cnn', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('fecha_entrenamiento', sa.DateTime(), nullable=False),
    sa.Column('exactitud_validacion', sa.Float(), nullable=False),
    sa.Column('archivo_pesos', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('activo IN (0, 1)', name='ck_modelo_cnn_activo'),
    sa.CheckConstraint('exactitud_validacion >= 0 AND exactitud_validacion <= 100', name='ck_modelo_cnn_exactitud'),
    sa.PrimaryKeyConstraint('id_modelo_cnn'),
    sa.UniqueConstraint('version')
    )
    op.create_index('idx_modelo_cnn_activo_unico', 'modelo_cnn', ['activo'], unique=True, sqlite_where=sa.text('activo = 1'))
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proveedor_oauth', sa.Text(), nullable=False),
    sa.Column('id_externo_proveedor', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.CheckConstraint("proveedor_oauth IN ('google', 'github')", name='ck_usuario_proveedor_oauth'),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('proveedor_oauth', 'id_externo_proveedor', name='uq_usuario_proveedor_externo')
    )
    op.create_table('modelo',
    sa.Column('id_modelo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_marca', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('cilindraje', sa.Integer(), nullable=False),
    sa.CheckConstraint('cilindraje IN (125, 150, 200)', name='ck_modelo_cilindraje'),
    sa.ForeignKeyConstraint(['id_marca'], ['marca.id_marca'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_modelo'),
    sa.UniqueConstraint('id_marca', 'nombre', name='uq_modelo_marca_nombre')
    )
    op.create_index('idx_modelo_marca', 'modelo', ['id_marca'], unique=False)
    op.create_table('diagnostico',
    sa.Column('id_diagnostico', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_modelo', sa.Integer(), nullable=False),
    sa.Column('id_modelo_cnn', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('kilometraje', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('audio_ref', sa.Text(), nullable=False),
    sa.Column('resultado', sa.Text(), nullable=False),
    sa.Column('confianza', sa.Float(), nullable=False),
    sa.Column('fecha_diagnostico', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("resultado IN ('normal', 'anomalia')", name='ck_diagnostico_resultado'),
    sa.CheckConstraint('anio >= 1980 AND anio <= 2100', name='ck_diagnostico_anio'),
    sa.CheckConstraint('confianza >= 0 AND confianza <= 100', name='ck_diagnostico_confianza'),
    sa.CheckConstraint('kilometraje IS NULL OR kilometraje >= 0', name='ck_diagnostico_kilometraje'),
    sa.ForeignKeyConstraint(['id_modelo'], ['modelo.id_modelo'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_modelo_cnn'], ['modelo_cnn.id_modelo_cnn'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_diagnostico')
    )
    op.create_index('idx_diagnostico_modelo', 'diagnostico', ['id_modelo'], unique=False)
    op.create_index('idx_diagnostico_modelo_cnn', 'diagnostico', ['id_modelo_cnn'], unique=False)
    # ### end Alembic commands ###

    # Indice por expresion (fecha DESC) para el historial; autogenerate no lo
    # soporta en SQLite, por eso se crea con SQL explicito.
    op.execute(
        "CREATE INDEX idx_diagnostico_usuario_fecha "
        "ON diagnostico (id_usuario, fecha_diagnostico DESC)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_diagnostico_usuario_fecha")
    op.drop_index('idx_diagnostico_modelo_cnn', table_name='diagnostico')
    op.drop_index('idx_diagnostico_modelo', table_name='diagnostico')
    op.drop_table('diagnostico')
    op.drop_index('idx_modelo_marca', table_name='modelo')
    op.drop_table('modelo')
    op.drop_table('usuario')
    op.drop_index('idx_modelo_cnn_activo_unico', table_name='modelo_cnn', sqlite_where=sa.text('activo = 1'))
    op.drop_table('modelo_cnn')
    op.drop_table('marca')
    # ### end Alembic commands ###
